technology-page
minimal-dev/chainflix pull request #6
Opened 2020-11-09 15:21 UTC by animetalist

2020-11-09 15:24 UTC, minimal-dev commented
Task linked: [CU-9yrub4 Technology](https://app.clickup.com/t/9yrub4)

2020-11-10 20:37 UTC, salexpro requested changes
- ![image](https://user-images.githubusercontent.com/4237964/98730460-fc557600-23a4-11eb-950d-21ade7350020.png)
 не по центру
- сделать линки на страницу

2020-11-10 20:38 UTC, salexpro commented
![image](https://user-images.githubusercontent.com/4237964/98730789-72f27380-23a5-11eb-9003-8186607c7bf8.png)

2020-11-12 15:51 UTC, salexpro requested changes
Пофиксить svg на блоке

2020-11-12 15:56 UTC, salexpro approved these changes

2020-11-12 16:00 UTC, merged