ecosystem-page
minimal-dev/chainflix pull request #7
Opened 2020-11-09 15:26 UTC by animetalist

2020-11-09 15:26 UTC, minimal-dev commented
Task linked: [CU-9wucbh Ecosystem](https://app.clickup.com/t/9wucbh)

2020-11-10 20:59 UTC, salexpro requested changes
- ![image](https://user-images.githubusercontent.com/4237964/98732002-3de72080-23a7-11eb-8f05-fc03b519057e.png)
 полная херня, говорил же юзать max-width а не паддинги
- ссылки на страницу
- ![image](https://user-images.githubusercontent.com/4237964/98732606-0d53b680-23a8-11eb-9ffb-c026ea5decae.png)
 так лучше не делать: ты либо юзаешь dash_case либо snake-case либо camelCase, например айдишники обычно в camelCase а классы в dash_case, по крайней мере у нас в проектах

2020-11-10 20:59 UTC, salexpro commented on src/assets/img/icons.svg
> +  </symbol>
![image](https://user-images.githubusercontent.com/4237964/98732450-d54c7380-23a7-11eb-89f5-76eb3d8fe46e.png)

тоже херня, сделать нормально, я вроде говорил что у всех иконок есть фрейм формы квадрата, в данном случае это 24х24

2020-11-10 20:59 UTC, salexpro commented on src/scss/sections/ecosystem/_hero.scss
> +}
если ты юзаешь его не только в этой секции тогда вынеси куда то на уровень вышел, если только тут тогда надо `.ecoHero_inner`

2020-11-10 21:00 UTC, salexpro commented on src/assets/img/icons.svg
> +  </symbol>
еще и размер не как в макете

2020-11-12 15:13 UTC, salexpro approved these changes

2020-11-12 15:19 UTC, merged