overview-page
minimal-dev/chainflix pull request #8
Opened 2020-11-09 15:29 UTC by animetalist

2020-11-09 15:29 UTC, minimal-dev commented
Task linked: [CU-9wuca1 Overview](https://app.clickup.com/t/9wuca1)

2020-11-10 21:08 UTC, salexpro requested changes
![image](https://user-images.githubusercontent.com/4237964/98733280-f5c8fd80-23a8-11eb-91a3-8b3839ed6233.png)
![image](https://user-images.githubusercontent.com/4237964/98733293-fc577500-23a8-11eb-92c5-e3bdce55876b.png)
- сходство с макетом минимальное
- линки

2020-11-10 21:08 UTC, salexpro commented on src/pug/sections/overview/_hero.pug
> +  .ovHero_pic
та же фигня с camelCase

2020-11-10 21:08 UTC, salexpro commented on src/scss/sections/overview/_hero.scss
> +    grid-template-areas: 'pic' 'content';
почему в одну строку не понятно но ладно не критично

2020-11-12 14:57 UTC, salexpro approved these changes

2020-11-12 15:04 UTC, merged