press-page
minimal-dev/chainflix pull request #9
Opened 2020-11-10 16:50 UTC by animetalist

2020-11-10 16:50 UTC, minimal-dev commented
Task linked: [CU-9wuc7k Press & Media](https://app.clickup.com/t/9wuc7k)

2020-11-10 21:23 UTC, salexpro requested changes
- уточнить на счет логосов в слайдере
- ![image](https://user-images.githubusercontent.com/4237964/98734257-602e6d80-23aa-11eb-9c0e-455a9b0eaab3.png)
 почему не в components как на том же мобиус?
- тоже странный нейминг картинок, если они и так в press папке находятся то логиченее было бы bg_lg.png что то типа такого, и да, для фонов используем префикс `bg_`

2020-11-10 21:23 UTC, salexpro commented on src/js/app.js
> +import './lib/_tabs';
компонентс

2020-11-10 21:23 UTC, salexpro commented on src/pug/sections/press/_hero.pug
> +  }]
особо смысла в такой конструкции нет с повторениями

2020-11-10 21:23 UTC, salexpro commented on src/scss/sections/press/_press.scss
> +    & svg {
амперсант тут не нужен

2020-11-10 21:23 UTC, salexpro commented on src/scss/sections/press/_press.scss
> +  }
шо це вобще, забудь за стили на тег img вообще

2020-11-12 14:53 UTC, salexpro approved these changes

2020-11-12 14:53 UTC, merged